services:
  # Serviço do Frontend
  frontend:
    image: frontend_image
    pull_policy: never
    container_name: frontend_container
    ports:
      - "5500:5500"
    networks:
      - ecommerce-network

  # Serviço de Login
  micro_login:
    image: micro_login_image
    pull_policy: never
    container_name: micro_login_container
    ports:
      - "8000:8000"
    networks:
      - ecommerce-network

  # Serviço de Envio de Produtos
  micro_sendproduto:
    image: sendproduto_image
    pull_policy: never
    container_name: micro_sendproduto_container
    ports:
      - "8001:8001"
    networks:
      - ecommerce-network

  # Serviço de Recebimento de Produtos
  sistema_main:
    image: sistema_main_image
    pull_policy: never
    container_name: sistema_main_container
    ports:
      - "8002:8002"
    networks:
      - ecommerce-network

  # Serviço de Validação de Cartões
  micro_pgt_cards:
    image: micro_pgt_cards_image
    pull_policy: never
    container_name: micro_pgt_cards_container
    ports:
      - "8003:8003"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
